<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>true</IsPackable>
<Version>1.1.1</Version>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Vestigium.Helpers.Tests" />
	</ItemGroup>

	<ItemGroup>
		<None Include="EventCatalog\logparser.json" Pack="true" PackagePath="contentFiles\any\any\EventCatalog\" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
