<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <VestigiumLoggingVersion>1.7.1</VestigiumLoggingVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Vestigium.Logging" Version="$(VestigiumLoggingVersion)" />
  </ItemGroup>
</Project>
