<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <VestigiumLoggingProject Condition="Exists('$(MSBuildThisFileDirectory)_deps\Vestigium.Logging\src\Vestigium.Logging\Vestigium.Logging.csproj')">$(MSBuildThisFileDirectory)_deps\Vestigium.Logging\src\Vestigium.Logging\Vestigium.Logging.csproj</VestigiumLoggingProject>
    <VestigiumLoggingProject Condition="'$(VestigiumLoggingProject)' == '' And Exists('$(MSBuildThisFileDirectory)..\Vestigium.Logging\src\Vestigium.Logging\Vestigium.Logging.csproj')">$(MSBuildThisFileDirectory)..\Vestigium.Logging\src\Vestigium.Logging\Vestigium.Logging.csproj</VestigiumLoggingProject>
  </PropertyGroup>
</Project>
