<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Vestigium\Helpers\Analytics\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Analytics\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Analytics\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Analytics\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Charts\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Charts\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Charts\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Charts\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Charts\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Charts\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Charts\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Charts\004 --Developers Guide\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\004 --Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Csv\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Csv\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Csv\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Csv\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Csv\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Csv\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Csv\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Csv\004 --Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Encryption\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Encryption\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Encryption\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Encryption\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Encryption\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Encryption\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Encryption\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Encryption\004 --Developers Guide\" />
    <Folder Include="Vestigium\Helpers\FileIo\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\FileIo\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\FileIo\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\FileIo\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\FileIo\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\FileIo\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\FileIo\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\FileIo\004 --Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Hashing\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Hashing\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Hashing\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Hashing\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Hashing\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Hashing\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Hashing\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Hashing\004 --Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Json\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Json\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Json\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Json\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Json\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Json\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Json\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Json\004 --Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Kql\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Kql\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Kql\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Kql\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Kql\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Kql\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Kql\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Kql\004 --Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Network\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Network\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Network\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Network\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Network\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Network\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Network\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Network\004 --Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Processes\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Processes\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Processes\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Processes\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Processes\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Processes\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Processes\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Processes\004 --Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Services\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Services\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Services\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Services\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Services\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Services\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Services\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Services\004 --Developers Guide\" />
    <Folder Include="Vestigium\Helpers\WinReg\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\WinReg\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\WinReg\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\WinReg\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\WinReg\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\WinReg\002 - Requirements Document\" />
    <Folder Include="Vestigium\Helpers\WinReg\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\WinReg\004 --Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Xml\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Xml\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Xml\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Xml\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Xml\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Xml\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Xml\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Xml\004 --Developers Guide\" />
  </ItemGroup>

</Project>
