<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\src\Vestigium.Helpers.Analytics\README.md" Link="Vestigium\Helpers\Analytics\README.md" />
    <Content Include="..\src\Vestigium.Helpers.Charts\README.md" Link="Vestigium\Helpers\Charts\README.md" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Vestigium\Helpers\Analytics\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Analytics\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Charts\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Charts\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\ClosedXml\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Csv\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Csv\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Csv\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Csv\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Csv\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Csv\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Encryption\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Encryption\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Encryption\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Encryption\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Encryption\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Encryption\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\FileIo\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\FileIo\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Hashing\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Hashing\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Hashing\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Json\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Json\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Json\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Json\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Json\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Kql\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Kql\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Kql\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Kql\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Network\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Network\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Network\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Network\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Processes\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Processes\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Processes\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Services\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Services\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Services\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\WinReg\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\WinReg\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Xml\000 -- Archived\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Xml\000 -- Archived\002 -- Requirements Document\" />
    <Folder Include="Vestigium\Helpers\Xml\000 -- Archived\003 -- Design Document\" />
    <Folder Include="Vestigium\Helpers\Xml\000 -- Archived\004 -- Developers Guide\" />
    <Folder Include="Vestigium\Helpers\Xml\001 -- Implementation Plan\" />
    <Folder Include="Vestigium\Helpers\Xml\003 -- Design Document\" />
  </ItemGroup>

</Project>
